import { Analytics } from "@vercel/analytics/react"
import type { Metadata } from "next"
import { Kosugi_Maru } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"
import Providers from "./providers"

const scorpius = localFont({
  src: "./fonts/Scorpius.woff",
  variable: "--font-scorpius"
})

const tram = localFont({
  src: "./fonts/Tram.woff",
  variable: "--font-tram"
})

const kosugiMaru = Kosugi_Maru({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-kosugi-maru"
})

const goozette = localFont({
  src: "./fonts/Goozette.woff",
  variable: "--font-goozette"
})

export const metadata: Metadata = {
  title: "Who do you have a crush on?",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Providers>
      <html lang="en">
        <head>
          <link rel="preload" as="image" href="/beach-heart.png" />
          <link rel="preload" as="image" href="/woods-heart.png" />
          <link rel="preload" as="image" href="/berlin1-heart.png" />
          <link rel="preload" as="image" href="/berlin-heart.png" />
        </head>
        <body
          className={`${scorpius.variable} ${tram.variable} ${kosugiMaru.variable} ${goozette.variable} antialiased`}
        >
          {children}
          <Analytics />
        </body>
      </html>
    </Providers>
  )
}
