import type { Metadata } from "next"
import { Kosugi_Maru } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"

const scorpius = localFont({
  src: "./fonts/Scorpius.woff",
  variable: "--font-scorpius"
})

const tram = localFont({
  src: "./fonts/Tram.woff",
  variable: "--font-tram"
})

const kosugiMaru = Kosugi_Maru({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-kosugi-maru"
})

export const metadata: Metadata = {
  title: "Who do you have a crush on?",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${scorpius.variable} ${tram.variable} ${kosugiMaru.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
